import math

WIDTH = 1200
HEIGHT = 600
PLAYER_SIZE = 30, 30
FPS = 60
FOV = math.pi / 3
NUM_RAYS = 240
MAX_DEPTH = 800
DELTA_ANGLE = FOV / NUM_RAYS
MAZE_WIDTH = MAZE_HEIGHT = 15
TILE_SIZE = WIDTH / MAZE_WIDTH
MAZE_START = 0, 0
NEIGHBOURS = [(0, 1), (1, 0), (0, -1), (-1, 0)]
DIST = NUM_RAYS / (2 * math.tan(FOV / 2))
PROJ_COEFF = DIST * TILE_SIZE * 3
PROJ_SCALE = WIDTH // NUM_RAYS
SENSITIVITY = 0.0007